In [9]:
import numpy as np

In [11]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np1.shape)

(10,)


In [15]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(np2.shape)

(2, 5)


In [19]:
np3 = np.arange(10,0,-1)
print(np3)

[10  9  8  7  6  5  4  3  2  1]


In [21]:
np4 = np.power(np1,np3)
print(np4)

[   0    1  256 2187 4096 3125 1296  343   64    9]
